# syntax=docker/dockerfile:1

FROM openjdk:16-alpine3.13
WORKDIR /app

# Get Maven wrapper and pom.xml file into our image.
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Install dependencies into the image.
# The `go-offline` goal of the Maven Dependency plugin downloads all the required dependencies and plugins for the project, based on the pom file.
RUN ./mvnw dependency:go-offline

# Add our source code into the image
COPY src ./src

# Tell Docker what command we want to run when our image is executed inside a container.
# Activate the MySQL Spring profile.
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=mysql"]
